# TODO: INSTALL SDL_IMAGE AND TFF
echo [Compile.sh] Deleting old executable...
del build\game.exe
echo [Compile.sh] Compiling game...
g++ -g src/*.cpp -o build/game -Iinclude `sdl2-config --cflags --libs`
echo [Compile.sh] Running game...

chmod +x build/game 
./build/game